# Project Trinitas v2.0 - Configuration Template
# Copy to ~/.claude/agents/trinitas/config.yaml after installation

# Core Trinitas Configuration
trinitas:
  # Operation mode: full (complete analysis), efficient (balanced), minimal (basic)
  mode: "full"
  
  # Enable automatic coordination between agents
  auto_coordination: true
  
  # Enable quality gates and validation
  quality_gates: true
  
  # Coordination threshold (0.0-1.0) - higher values require more explicit triggers
  coordination_threshold: 0.8

# Individual Persona Configuration
personalities:
  
  # Springfield - Strategic Coordinator
  springfield:
    # Communication formality: casual, polite, formal
    formality: "polite"
    
    # Primary language: english, japanese, mixed
    language: "japanese"
    
    # Strategic focus areas
    focus_areas:
      - "long_term_planning"
      - "team_coordination" 
      - "stakeholder_management"
      - "risk_communication"
    
  # Krukai - Technical Optimizer
  krukai:
    # Quality standards: relaxed, standard, strict
    standards: "strict"
    
    # Optimization level: disabled, enabled, aggressive
    optimization: "aggressive"
    
    # Performance focus areas
    focus_areas:
      - "code_quality"
      - "performance_optimization"
      - "technical_excellence"
      - "implementation_efficiency"
    
  # Vector - Security Auditor
  vector:
    # Paranoia level for risk assessment: low, medium, high
    paranoia_level: "high"
    
    # Compliance frameworks to consider
    compliance:
      - "OWASP"
      - "GDPR"
      - "SOX"
      - "NIST"
    
    # Security focus areas
    focus_areas:
      - "vulnerability_assessment"
      - "threat_modeling"
      - "risk_analysis"
      - "compliance_validation"

# Agent Auto-Detection Configuration
agent_config:
  
  trinitas_coordinator:
    # Threshold for automatic activation (0.0-1.0)
    auto_trigger_threshold: 0.8
    
    # Keywords that trigger this agent
    keywords:
      - "comprehensive"
      - "trinitas"
      - "three perspectives"
      - "multi-perspective"
      - "strategic technical security"
    
    # Required context patterns
    context_patterns:
      - "analysis"
      - "evaluation"
      - "assessment"
      - "review"
  
  springfield_strategist:
    auto_trigger_threshold: 0.7
    keywords:
      - "strategy"
      - "planning"
      - "roadmap"
      - "long-term"
      - "vision"
      - "architecture"
      - "stakeholder"
    context_patterns:
      - "plan"
      - "strategy"
      - "future"
      - "goal"
  
  krukai_optimizer:
    auto_trigger_threshold: 0.7
    keywords:
      - "performance"
      - "optimization"
      - "quality"
      - "technical"
      - "efficiency"
      - "code review"
      - "implementation"
    context_patterns:
      - "optimize"
      - "improve"
      - "enhance"
      - "refactor"
  
  vector_auditor:
    auto_trigger_threshold: 0.9
    keywords:
      - "security"
      - "audit"
      - "risk"
      - "vulnerability"
      - "threat"
      - "compliance"
      - "safety"
    context_patterns:
      - "secure"
      - "protect"
      - "validate"
      - "verify"
  
  trinitas_workflow:
    auto_trigger_threshold: 0.6
    keywords:
      - "workflow"
      - "pipeline"
      - "automation"
      - "process"
      - "lifecycle"
      - "CI/CD"
      - "deployment"
    context_patterns:
      - "automate"
      - "streamline"
      - "manage"
      - "coordinate"
  
  trinitas_quality:
    auto_trigger_threshold: 0.7
    keywords:
      - "quality"
      - "testing"
      - "validation"
      - "QA"
      - "assurance"
      - "verification"
      - "standards"
    context_patterns:
      - "test"
      - "validate"
      - "check"
      - "verify"

# Quality Gates Configuration
quality_gates:
  # Enable individual quality gate steps
  enabled_gates:
    syntax_validation: true
    type_safety: true
    code_quality: true
    security_validation: true
    testing_validation: true
    performance_validation: true
    integration_testing: true
    documentation_validation: true
  
  # Quality thresholds
  thresholds:
    code_quality_score: 0.80
    test_coverage_unit: 0.90
    test_coverage_integration: 0.70
    security_score: 0.90
    performance_score: 0.85
  
  # Failure handling
  on_failure:
    action: "report"  # report, block, warn
    notification: true
    retry_attempts: 2

# Automation Configuration
automation:
  # Pre-execution hooks
  pre_execution:
    dangerous_command_check: true
    resource_validation: true
    security_clearance: true
    context_preparation: true
  
  # Post-execution hooks
  post_execution:
    quality_validation: true
    knowledge_persistence: true
    progress_notification: true
    cleanup: true
  
  # Notification settings
  notifications:
    enabled: true
    channels: ["console"]  # console, file, webhook
    verbosity: "normal"  # minimal, normal, verbose

# Integration Configuration
integrations:
  # Version control
  git:
    enabled: true
    auto_commit: false
    commit_message_template: "feat: {description}\n\nTrinitas automated commit\n\nCo-authored-by: Springfield <strategy@trinitas.dev>\nCo-authored-by: Krukai <technical@trinitas.dev>\nCo-authored-by: Vector <security@trinitas.dev>"
  
  # CI/CD systems
  cicd:
    enabled: false
    systems: []  # github_actions, gitlab_ci, jenkins
  
  # Project management
  project_management:
    enabled: false
    systems: []  # jira, github_issues, linear

# Logging Configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"
  
  # Log destinations
  destinations:
    console: true
    file: true
    file_path: "~/.claude/agents/trinitas/logs/trinitas.log"
  
  # Log rotation
  rotation:
    enabled: true
    max_size: "10MB"
    backup_count: 5

# Performance Configuration
performance:
  # Enable caching
  cache_enabled: true
  cache_ttl: 3600  # seconds
  
  # Parallel processing
  parallel_operations: true
  max_workers: 3
  
  # Timeout settings
  timeouts:
    agent_response: 30  # seconds
    coordination: 60    # seconds
    quality_gates: 120  # seconds

# Security Configuration
security:
  # Validation settings
  validate_inputs: true
  sanitize_outputs: true
  
  # Audit logging
  audit_logging: true
  audit_log_path: "~/.claude/agents/trinitas/logs/audit.log"
  
  # Dangerous command protection
  dangerous_commands:
    enabled: true
    block_list:
      - "rm -rf /"
      - "sudo rm -rf"
      - "format c:"
      - "del /f /s /q C:\\"
    
    # Action on dangerous command: block, warn, log
    action: "block"

# Development Configuration (for Trinitas development)
development:
  # Debug mode
  debug: false
  
  # Test mode (reduces thresholds, increases verbosity)
  test_mode: false
  
  # Development logging
  dev_logging: false