version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: trinitas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - trinitas-network

  # Optional: Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: trinitas-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - trinitas-network
    profiles:
      - debug

volumes:
  redis_data:
    name: trinitas_redis_data

networks:
  trinitas-network:
    name: trinitas_network
    driver: bridge