# Trinitas Project Configuration
# System-wide configuration for MCP Tools

system:
  name: "Trinitas Project"
  version: "3.5"
  description: "Three-mind integrated intelligence system for development"
  
# Execution Modes
modes:
  full_local:
    name: "Full Local"
    description: "Local LLM for extended team, simulation for trinity"
    requires_local_llm: true
    
  claude_only:
    name: "Claude Only"
    description: "All personas executed by Claude's native intelligence"
    requires_local_llm: false
    
  simulation:
    name: "Simulation"
    description: "Lightweight simulation for all personas"
    requires_local_llm: false
    
  hybrid:
    name: "Hybrid"
    description: "Claude for trinity core, simulation for others"
    requires_local_llm: false
    
  auto:
    name: "Auto"
    description: "Automatic selection based on availability"
    requires_local_llm: false

# Local LLM Configuration
local_llm:
  endpoint: "${LOCAL_LLM_ENDPOINT:-http://192.168.99.102:1234/v1/}"
  model: "${LOCAL_LLM_MODEL:-openai/gpt-oss-120b}"
  temperature: 0.7
  max_tokens: 2000
  timeout: 30
  
# Performance Settings
performance:
  cache_ttl: 300  # seconds
  max_cache_size: 100  # MB
  batch_size: 5
  parallel_limit: 3
  
# Logging Configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "trinitas.log"
  
# API Settings
api:
  timeout: 30
  retry_count: 3
  retry_delay: 1
  
# Feature Flags
features:
  enable_caching: true
  enable_performance_monitoring: true
  enable_quality_gates: true
  enable_auto_mode: true
  
# Persona Mapping (references personas.yaml)
persona_mapping:
  trinity_core:
    - athena      # Strategic Architect
    - artemis     # Technical Perfectionist
    - hestia      # Paranoid Guardian
    
  extended_team:
    - bellona     # Tactical Coordinator
    - seshat      # Documentation Specialist
    
# Deployment Settings
deployment:
  environment: "${TRINITAS_ENV:-development}"
  debug_mode: "${DEBUG:-false}"
  standalone_mode: true  # No external dependencies
  
# Security Settings
security:
  enable_input_validation: true
  enable_output_sanitization: true
  max_input_length: 10000
  allowed_file_types:
    - .py
    - .md
    - .yaml
    - .yml
    - .json
    - .txt
    
# Collaboration Settings
collaboration:
  sequential_delay: 0.1  # seconds between sequential executions
  parallel_timeout: 10   # seconds for parallel execution
  max_personas: 5        # maximum personas in collaboration