# Trinitas v3.5 - Naming Mode Configuration
# Controls whether to use mythology names or Dolls Frontline 2 names

naming:
  # Default naming mode
  # Options: mythology, developer, auto
  default_mode: mythology
  
  # Allow runtime switching between modes
  allow_runtime_switch: true
  
  # Log name conversions for debugging
  log_conversions: false
  
  # Developer mode settings
  developer_mode:
    # Use Japanese names for locations
    use_japanese_locations: true
    
    # Show original Dolls Frontline 2 backstories
    show_original_backstory: true
    
    # Display format for personas
    persona_format: "{name} - {title}"  # e.g., "Springfield - Strategic Architect"
    
    # Organization name style
    organization_style: full  # full: "Griffin Systems", short: "Griffin"
  
  # Mythology mode settings  
  mythology_mode:
    # Use full deity titles
    use_full_titles: false  # true: "Athena, Goddess of Wisdom"
    
    # Display format for personas
    persona_format: "{name} - {title}"  # e.g., "Athena - Strategic Architect"
    
    # Show mythology references
    show_mythology_info: false
  
  # Auto mode settings
  auto_mode:
    # Detection rules for automatic mode selection
    detect_from_context: true
    
    # Keywords that trigger developer mode
    developer_keywords:
      - "dolls frontline"
      - "ドルフロ"
      - "griffin"
      - "404"
      - "エルモ"
      - "ズッケロ"
    
    # Keywords that trigger mythology mode
    mythology_keywords:
      - "olympus"
      - "athena"
      - "artemis"
      - "aegis"
      - "prometheus"

# Display overrides (optional)
# These override the default display names
display_overrides:
  # Example:
  # athena: "Athena (Springfield)"  # Shows both names